### ISSUE TITLE
failed installation

### ISSUE THREAD

**Issue by pmarcum** [y-js/latex-editor#2]
After executing "npm i -g latex-editor" in the Node.js command prompt window (operating system is Windows 10), I get a "Failed at the leveldown@1.4.6 install script 'prebuild --install'" error.  I do have the latest versions of node.js and npm (doing a "node -v" and "npm -v" show v4.4.7 and 3.10.7, respectively).  When I just ignored the error to see if "latex-editor" would run, I got  the following error: " Cannot find module 'C:\Users[user]\AppData\Roaming\npm\node_modules\latex-editor\latex-editor.js' at Function.Module._resolveFilename (module.js:323:15) at Function.Module._load (module.js:276:25) at Function.Module.runMain (module.js:441:10) at startup (node.js:139:18) at node.js:968:3
Any ideas as to what went wrong? (I am squarely into territory for which I have zero expertise, unfortunately).

**Comment by dmonad** [comment]
One of the dependencies requires leveldb, which is compiled directly on your computer. You probably need _msbuild tools_ in order to do that on Windows. I made that dependency optional, so you should be able to install latex-editor now.

I'm unable to test this though. Please comment in this thread if the installation still fails! (Note: the error will still occur, but the installation will continue)

**Comment by pmarcum** [comment]
thanks!  I'll install msbuild tools and give it a go. 

```
  From: Kevin Jahns <notifications@github.com>
```

 To: y-js/latex-editor latex-editor@noreply.github.com 
Cc: pmarcum mucramap@yahoo.com; Author author@noreply.github.com
 Sent: Monday, August 15, 2016 7:20 AM
 Subject: Re: [y-js/latex-editor] failed installation (#2)

One of the dependencies requires leveldb, which is compiled directly on your computer. You probably need msbuild tools in order to do that on Windows. I made that dependency optional, so you should be able to install latex-editor now.I'm unable to test this though. Please comment in this thread if the installation still fails! (Note: the error will still occur, but the installation will continue)—

**Comment by dmonad** [comment]
Oh sorry, I didn't explain it well. You can install it now without msbuild tools. You will still get an error/warning, but you can safely ignore it (because the dependency is optional now).

**Comment by pmarcum** [comment]
Oh, got it -- thanks!  (I already installed mdbuild tools following your email, and assumed that is why it was working now!).  

thanks again, 
--Pam 

```
  From: Kevin Jahns <notifications@github.com>
```

 To: y-js/latex-editor latex-editor@noreply.github.com 
Cc: pmarcum mucramap@yahoo.com; Author author@noreply.github.com
 Sent: Tuesday, August 16, 2016 9:05 AM
 Subject: Re: [y-js/latex-editor] failed installation (#2)

Oh sorry, maybe I didn't explain it well. You can install it now without msbuild tools. You will still get an error/warning, but you can safely ignore it.—
